version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9.10
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rabbitmq
    hostname: rabbitmq
    restart: always
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
    environment:
      RABBITMQ_ERLANG_COOKIE: "secret_cookie"
      RABBITMQ_DEFAULT_USER: "admin"
      RABBITMQ_DEFAULT_PASS: "password"
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  rabbitmq_data:
